# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0611f0c6e9c72df27de42b6153120f9cb8dab795680a2732401e8133e30b78ab449872c1db2a57cc7f52f9ccace1cc5cc77661a42ca90a58c21978fa8fa3f9bf

test:
  secret_key_base: 92c24e800c0378f9421f04123d344796512fd23c266d32426a5c8dbc64bd30ec098ebb27e7326287e361bc72e0579db15e30cb8cd19ff79d5cda9a96aa6b5d30

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
